//
//  LoginWorker.swift
//  SummerBagFinder
//
//  Created by EUIGYOM KIM on 2020/06/21.
//  Copyright (c) 2020 EUIGYOM KIM. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Moya



class LoginWorker {
    func processToLogin(id: String?, password: String?, completion: @escaping (Result<Bool, Error>) -> ()) {
        guard let id = id, let password = password else { return }
        
        let provider = MoyaProvider<StarbucksService>()
        provider.request(.login(id, password)) { result in
            switch result {
            case .success(let response):
                guard let data = try? response.map(BaseResponse.self) else {
                    completion(.failure(BaseError.serverError(message: nil)))
                    return
                }
                
                let receiveSuccessResponse = data.resultCode == "SUCCESS"
                completion(.success(receiveSuccessResponse))
            case .failure(let error):
                completion(.failure(BaseError.serverError(message: error.errorDescription)))
            }
        }
    }
    
}
