//
//  LoginRouter.swift
//  SummerBagFinder
//
//  Created by EUIGYOM KIM on 2020/06/21.
//  Copyright (c) 2020 EUIGYOM KIM. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginRoutingLogic: RoutingLogic {
    func routeToRegionList()
}

class LoginRouter: NSObject, LoginRoutingLogic {
    var viewController: UIViewController
    private var regionSelectBuilder: RegionSelectBuilable
    
    init(viewController: UIViewController, regionSelectBuilder: RegionSelectBuilable) {
        self.viewController = viewController
        self.regionSelectBuilder = regionSelectBuilder
    }
    
    // MARK: Routing
    func routeToRegionList() {
        let router = regionSelectBuilder.build()
        let regionsVC = router.viewController
        viewController.navigationController?.pushViewController(regionsVC, animated: true)
    }
}
