//
//  LoginPresenter.swift
//  SummerBagFinder
//
//  Created by EUIGYOM KIM on 2020/06/21.
//  Copyright (c) 2020 EUIGYOM KIM. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

class LoginPresenter: LoginPresentationLogic {
    weak var viewController: LoginDisplayLogic?
    
    func present(_ response: Login.Response) {
        switch response {
        case let .error(error):
            let viewModel = CommonViewModel.Alert(
                id: 100,
                title: "알림",
                message: error.description,
                confirmTitle: "확인"
            )
            viewController?.display(viewModel)
        }
    }
}

// MARK: LoginDisplayLogic

protocol LoginDisplayLogic: class {
    func display(_ viewModel: CommonViewModel.Alert)
}
