//
//  LoginInteractor.swift
//  SummerBagFinder
//
//  Created by EUIGYOM KIM on 2020/06/21.
//  Copyright (c) 2020 EUIGYOM KIM. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginBusinessLogic {
    func doLogin(request: Login.LoginTrial.Request)
}

class LoginInteractor {
    var presenter: LoginPresentationLogic?
    var router: LoginRoutingLogic?
    var worker: LoginWorker?
    
    init() {
        worker = LoginWorker()
    }
}

extension LoginInteractor: LoginBusinessLogic {
    func doLogin(request: Login.LoginTrial.Request) {
        worker?.processToLogin(id: request.id, password: request.password) { [weak self] result in
            guard let self = self else { return }
            guard case let .success(isSuccess) = result else {
                self.presenter?.presentLoginFailure()
                return
            }
            
            // 지역 선택 화면으로 이동
            if isSuccess {
                self.router?.routeToRegionList(message: "로그인화면에서 온 메시지")
            }
                
            // 로그인 실패 얼럿 노출
            else {
                self.presenter?.presentLoginFailure()
            }
        }
    }
}
