//
//  LoginPresenter.swift
//  SummerBagFinder
//
//  Created by EUIGYOM KIM on 2020/06/21.
//  Copyright (c) 2020 EUIGYOM KIM. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class LoginPresenter: LoginPresentationLogic {
    weak var viewController: LoginDisplayLogic?
    
    func displayLoginFailureAlert() {
        let viewModel = Login.ViewModel.LoginFailureMessage(
            title: "알림",
            message: "로그인에 실패했습니다.\n아이디와 패스워드를 다시 확인해 주세요.",
            confirmTitle: "확인"
        )
        viewController?.displayLoginFailureAlert(viewModel)
    }
}

// MARK: LoginDisplayLogic

protocol LoginDisplayLogic: class {
    func displayLoginFailureAlert(_ viewModel: Login.ViewModel.LoginFailureMessage)
}
