//
//  StoreListInteractor.swift
//  SummerBagFinder
//
//  Created by EUIGYOM KIM on 2020/06/21.
//  Copyright (c) 2020 EUIGYOM KIM. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol StoreListBusinessLogic {
    func viewDidLoad()
    func didSelectStore(_ request: StoreList.didSelectStore.Request)
}

class StoreListInteractor {
    var router: (NSObjectProtocol & StoreListRoutingLogic)?
    var presenter: StoreListPresentationLogic?
    deinit {
        print(#function)
    }
    var stores: [Store]?
    
    init(stores: [Store]?) {
        self.stores = stores
    }
}

extension StoreListInteractor: StoreListBusinessLogic {
    
    func viewDidLoad() {
        
        if let stores = stores {
            let response = StoreList.viewDidLoad.Response(stores: stores)
            presenter?.displayStoreStockList(response)
        }
    }
    
    func didSelectStore(_ request: StoreList.didSelectStore.Request) {
        if let store = stores?[request.index] {
            router?.routeToStoreMap(store: store)
        }
    }
    
}
