//
//  StoreListRouter.swift
//  SummerBagFinder
//
//  Created by EUIGYOM KIM on 2020/06/21.
//  Copyright (c) 2020 EUIGYOM KIM. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import SwiftUI

protocol StoreListRoutingLogic {
    func routeToStoreMap(store: Store)
}

class StoreListRouter: NSObject, StoreListRoutingLogic {
    weak var viewController: UIViewController!
    
    deinit {
        print(#function)
    }
    
    init(viewController: UIViewController) {
        self.viewController = viewController
    }
    
    func routeToStoreMap(store: Store) {
        ///유킷  ->  스유
        let (interactor, presenter) = StoreMapScene().build(store: store)
        
        let destination = UIHostingController(rootView: StoreMapView(interactor: interactor, presenter: presenter))
        viewController.display(destination)
    }
}
