//
//  StoreListPresenter.swift
//  SummerBagFinder
//
//  Created by EUIGYOM KIM on 2020/06/21.
//  Copyright (c) 2020 EUIGYOM KIM. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class StoreListPresenter: StoreListPresentationLogic {
    weak var viewController: StoreListDisplayLogic?
    
    deinit {
        print(#function)
    }
    func displayStoreStockList(_ response: StoreList.viewDidLoad.Response) {
        let viewModel = StoreList.viewDidLoad.ViewModel(stores: response.stores)
        
        viewController?.displayStoreStockList(viewModel)
    }
}

// MARK: protocol

protocol StoreListDisplayLogic: class {
    func displayStoreStockList(_ viewModel: StoreList.viewDidLoad.ViewModel)
}
