//
//  StoreListModels.swift
//  SummerBagFinder
//
//  Created by EUIGYOM KIM on 2020/06/21.
//  Copyright (c) 2020 EUIGYOM KIM. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum StoreList {
    
    enum Request {
        struct OnLoad {}
        struct OnSelectStore {
            let index: Int
        }
    }
    
    enum Response {
        case stores([Store])
    }
    
    enum ViewModel {
        struct Stores {
            let stores: [Store]
        }

        struct Store {
            let name: String
            let address: String
            let stock: Stock
        }
        
        struct Stock {
            let status : String
            let iconColor: UIColor
        }
    }
}
