//
//  StoreListRouter.swift
//  SummerBagFinder
//
//  Created by EUIGYOM KIM on 2020/06/21.
//  Copyright (c) 2020 EUIGYOM KIM. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import SwiftUI

protocol StoreListRoutingLogic {
    func routeToStoreMap(store: Store)
}

class StoreListRouter: NSObject, StoreListRoutingLogic {
    var scene: StoreListSceneLogic
    
    deinit {
        print(#function)
    }
    
    init(scene: StoreListSceneLogic) {
        self.scene = scene
    }
    
    func routeToStoreMap(store: Store) {
        ///유킷  ->  스유
        let destinationVC = StoreMapScene().build(store: store)
        
        let destination = UIHostingController(rootView: StoreMapView(viewController: destinationVC))
        scene.viewController.display(destination)
    }
}
