//
//  RegionSelectModels.swift
//  SummerBagFinder
//
//  Created by EUIGYOM KIM on 2020/06/21.
//  Copyright (c) 2020 EUIGYOM KIM. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum RegionSelect {
    
    enum Request {
        struct OnLoad {}
        struct OnAppear {}
        struct OnSelectRegion {
            let indexPath: IndexPath
        }
    }
    
    enum Response {
        case regions([Region])
        case alert(message: String)
    }
    
    enum ViewModel {
        
        struct Regions {
            let regions: [Region]
        }
        
        struct Region {
            let name: String
            let subregions: [SubRegion]
        }
        
        struct SubRegion {
            let name: String
        }
    }
}


