//
//  RegionSelectInteractor.swift
//  SummerBagFinder
//
//  Created by EUIGYOM KIM on 2020/06/21.
//  Copyright (c) 2020 EUIGYOM KIM. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RegionSelectBusinessLogic {
    func viewWillAppear()
    func doFetchRegions()
    func doMoveToStoreList(_ request: RegionSelect.MoveStoreList.Request)
}

class RegionSelectInteractor: RegionSelectBusinessLogic {
    var router: (NSObjectProtocol & RegionSelectRoutingLogic)?
    var presenter: RegionSelectPresentationLogic?
    var worker: RegionSelectWorker?
    
    var regions: [Region] = []
    var stores: [Store]?
    
    private let message: String?
    
    init(message: String?) {
        worker = RegionSelectWorker()
        self.message = message
    }
    
    deinit {
        print(#function)
    }
    
    func viewWillAppear() {
        if let message = message {
            presenter?.showMessageAlert(message: message)
        }
    }
    
    func doFetchRegions() {

        worker?.fetchRegionList { [weak self] result in
            guard let self = self else { return }
            guard case let .success(regions) = result else { return }
            self.regions = regions
            let response = RegionSelect.doFetchRegions.Response(regions: regions)
            self.presenter?.presentRegionList(response)
        }
    }
    
    func doMoveToStoreList(_ request: RegionSelect.MoveStoreList.Request) {
        let indexPath = request.indexPath
        let subregion = regions[indexPath.section].subregions[indexPath.row]
        
        worker?.fetchStoreList(regionCode: subregion.id) { [weak self] result in
            guard let self = self else { return }
            guard case let .success(stores) = result else { return }
            
            self.stores = stores
            self.router?.routeToStoreList(stores: stores)
        }
    }
}
