//
//  RegionSelectModels.swift
//  SummerBagFinder
//
//  Created by EUIGYOM KIM on 2020/06/21.
//  Copyright (c) 2020 EUIGYOM KIM. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum RegionSelect {
    
    enum doFetchRegions {
        struct Request {}
        struct Response {
            let regions: [Region]
        }
        struct ViewModel {
            let regions: [RegionViewModel]
        }
    }
    
    enum MoveStoreList {
        struct Request {
            let indexPath: IndexPath
        }
        struct Response {}
        struct ViewModel {}
    }
}

struct RegionViewModel {
    let name: String
    let subregions: [SubregionViewModel]
    
    struct SubregionViewModel {
        let name: String
    }
}
