//
//  RegionSelectRouter.swift
//  SummerBagFinder
//
//  Created by EUIGYOM KIM on 2020/06/21.
//  Copyright (c) 2020 EUIGYOM KIM. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol RegionSelectRoutingLogic {
    func routeToStoreList()
}

protocol RegionSelectDataPassing {
    var dataStore: RegionSelectDataStore? { get }
}

class RegionSelectRouter: NSObject, RegionSelectRoutingLogic, RegionSelectDataPassing {
    weak var viewController: RegionSelectViewController?
    var dataStore: RegionSelectDataStore?
}

extension RegionSelectRouter {
    // MARK: Routing
    func routeToStoreList() {
        guard let viewController = viewController else { return }
        guard let dataStore = dataStore else { return }
        
        let destinationVC = StoreListViewController()
        var destinationDS = destinationVC.router!.dataStore!
        passDataToStoreList(source: dataStore, destination: &destinationDS)
        navigateToStoreList(source: viewController, destination: destinationVC)
    }
    
    // MARK: Navigation
    func navigateToStoreList(source: RegionSelectViewController, destination: StoreListViewController) {
        source.show(destination, sender: nil)
    }
    
    // MARK: Passing data
    func passDataToStoreList(source: RegionSelectDataStore, destination: inout StoreListDataStore) {
        destination.dataList = source.fetchedStockList
    }
}
