//
//  RegionSelectWorker.swift
//  SummerBagFinder
//
//  Created by EUIGYOM KIM on 2020/06/21.
//  Copyright (c) 2020 EUIGYOM KIM. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Moya

class RegionSelectWorker {
    func fetchRegionList(completion: @escaping (Result<[Region], Error>) -> ()) {
        guard let path = Bundle.main.path(forResource: "regions", ofType: "json") else {
            completion(.failure(BaseError.parseError))
            return
        }
        
        guard let jsonData = FileManager.default.contents(atPath: path) else {
            completion(.failure(BaseError.parseError))
            return
        }
        
        guard let regions = try? JSONDecoder().decode([Region].self, from: jsonData) else {
            completion(.failure(BaseError.parseError))
            return
        }
        
        completion(.success(regions))
    }
    
    func fetchStoreList(regionCode: String, completion: @escaping (Result<StoreStockList, Error>) -> ()) {
        let provider = MoyaProvider<StarbucksService>()
        provider.request(.getStockList(regionCode)) { result in
            switch result {
            case .success(let response):
                guard let data = try? response.map(StoreStockList.self) else {
                    completion(.failure(BaseError.parseError))
                    return
                }
                
                completion(.success(data))
            case .failure(let error):
                completion(.failure(BaseError.serverError(message: error.errorDescription)))
            }
        }
    }
}
