//
//  RegionSelectPresenter.swift
//  SummerBagFinder
//
//  Created by EUIGYOM KIM on 2020/06/21.
//  Copyright (c) 2020 EUIGYOM KIM. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RegionSelectPresentationLogic {
    func presentRegionList(_ response: RegionSelect.doFetchRegions.Response)
}

class RegionSelectPresenter: RegionSelectPresentationLogic {
    weak var viewController: RegionSelectDisplayLogic?
    
    func presentRegionList(_ response: RegionSelect.doFetchRegions.Response) {
        let regions = response.regions.map {
            RegionViewModel(
                name: $0.name,
                subregions: $0.subregions.map { RegionViewModel.SubregionViewModel(name: $0.name)}
            )
        }
        let viewModel = RegionSelect.doFetchRegions.ViewModel(regions: regions)
        viewController?.displayRegionList(viewModel)
    }
}
