//
//  RegionSelectModels.swift
//  SummerBagFinder
//
//  Created by EUIGYOM KIM on 2020/06/21.
//  Copyright (c) 2020 EUIGYOM KIM. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum RegionSelect {
    
    struct Region: Codable {
        let prefix: String
        let name: String
        let subregions: [Subregion]
        
        enum CodingKeys: String, CodingKey {
            case prefix
            case name = "region_name"
            case subregions
        }
    }
    
    struct Subregion: Codable {
        let id: String
        let name: String
    }
    
    // MARK: Use cases
    
    enum MoveStoreList {
        struct Request {
            let indexPath: IndexPath
        }
        struct Response {
            let stockList: StoreStockList
        }
        struct ViewModel {
            let stockList: StoreStockList
        }
    }
}
