//
//  StoreMapRouter.swift
//  
//
//  Created by mine on 2020/06/28.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import SwiftUI

protocol StoreMapRoutingLogic {
    #warning("구체타입.")
    var viewController: StoreMapViewController{ get }
    func routeToStoreDetail()
    func routeToRegionSelection(message: String?)
}

class StoreMapRouter: NSObject, StoreMapRoutingLogic {
    var viewController: StoreMapViewController
    var storeDetailBuilder: StoreDetailBuildingLogic
    var regionSelectBuilder: RegionSelectBuildingLogic

    init(viewController: StoreMapViewController, storeDetailBuilder: StoreDetailBuildingLogic, regionSelectBuilder: RegionSelectBuildingLogic) {
        self.viewController = viewController
        self.storeDetailBuilder = storeDetailBuilder
        self.regionSelectBuilder = regionSelectBuilder
    }
    
    func routeToStoreDetail() {
        let router = storeDetailBuilder.build()
        viewController.isStoreDetailPresented = true
        viewController.storeDetailViewController = router.viewController
    }
    
    func routeToRegionSelection(message: String?) {
        // 스유 -> 유킷
        let sceneBuildingLogic: () -> RegionSelectRoutingLogic = {
            let router = self.regionSelectBuilder.build(message: message)
            return router
        }
        viewController.isRegionSelectPresended = true
        viewController.regionSelectSceneBuildingLogic = sceneBuildingLogic
    }
}
