//
//  StoreMapRouter.swift
//  
//
//  Created by mine on 2020/06/28.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import SwiftUI

protocol StoreMapRoutingLogic {
    func routeToStoreDetail()
    func routeToRegionSelection(message: String?)
}

class StoreMapRouter: NSObject, StoreMapRoutingLogic {
    var scene: StoreMapSceneLogic
    var storeDetailScene: StoreDetailSceneLogic
    var regionSelectScene: RegionSelectSceneLogic

    init(scene: StoreMapSceneLogic, storeDetailScene: StoreDetailSceneLogic, regionSelectScene: RegionSelectSceneLogic) {
        self.scene = scene
        self.storeDetailScene = storeDetailScene
        self.regionSelectScene = regionSelectScene
    }
    
    func routeToStoreDetail() {
        // 스유 -> 스유 
        let storeDetailVC = storeDetailScene.build()
        self.scene.routerDelegate.isStoreDetailPresented = true
        self.scene.routerDelegate.storeDetailViewController = storeDetailVC
    }
    
    func routeToRegionSelection(message: String?) {
        // 스유 -> 유킷
        let sceneBuildingLogic: () -> RegionSelectViewController = {
            let viewController = self.regionSelectScene.build(message: message)
            return viewController
        }
        self.scene.routerDelegate.isRegionSelectPresended = true
        self.scene.routerDelegate.regionSelectSceneBuildingLogic = sceneBuildingLogic
    }
}
