//
//  StoreMapInteractor.swift
//  
//
//  Created by mine on 2020/06/28.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// MARK: StoreMapInteractor

class StoreMapInteractor: StoreMapBusinessLogic {
    var router: StoreMapRoutingLogic?
    var presenter: StoreMapPresentationLogic?
    var worker: StoreMapWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func didTapButton(_ request: StoreMap.Request.DidTapButton) {
        let store = Store(id: 100, name: "스타벅스 강남2호점", address: "강남역", isOpen: true, stock: Stock(totalCount: 100, greenCount: 40, pinkCount: 60))
        router?.routeToStoreDetail(store: store, listener: self)
    }
    
    func didTapRegionSelection(_ request: StoreMap.Request.DidTapRegionSelection) {
        router?.routeToRegionSelection(message: "Store Map에서 온 메시지")
    }
}

// MARK:

extension StoreMapInteractor: StoreDetailListener {
    
    func didFinishWriting(message: String) {
        let viewModel = StoreMap.ViewModel.FromDetail(message: message)
        presenter?.displayMessageFromDetail(viewModel)
    }
}

// MARK: protocol

protocol StoreMapBusinessLogic {
    func didTapButton(_ request: StoreMap.Request.DidTapButton)
    func didTapRegionSelection(_ request: StoreMap.Request.DidTapRegionSelection)
}

protocol StoreMapPresentationLogic {
    func displayMessageFromDetail(_ viewModel: StoreMap.ViewModel.FromDetail)
}

protocol StoreMapRoutingLogic {
    func routeToStoreDetail(store: Store, listener: StoreDetailListener?)
    func routeToRegionSelection(message: String?)
}
