//
//  StoreMapInteractor.swift
//  
//
//  Created by mine on 2020/06/28.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// MARK: StoreMapInteractor

class StoreMapInteractor: StoreMapBusinessLogic {
    var router: StoreMapRoutingLogic?
    var presenter: StoreMapPresentationLogic?
    var worker: StoreMapWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func didTapButton(_ request: StoreMap.DidTapButton.Request) {
        let store = Store(id: 100, name: "스타벅스 강남2호점", address: "강남역", isOpen: true, stock: Stock(totalCount: 100, greenCount: 40, pinkCount: 60))
        router?.routeToStoreDetail(store: store)
    }
    
    func didTapRegionSelection(_ request: StoreMap.DidTapRegionSelection.Request) {
        router?.routeToRegionSelection(message: "Store Map에서 온 메시지")
    }
}

// MARK: protocol

protocol StoreMapBusinessLogic {
    func didTapButton(_ request: StoreMap.DidTapButton.Request)
    func didTapRegionSelection(_ request: StoreMap.DidTapRegionSelection.Request)
}

protocol StoreMapPresentationLogic {
    func presentSomething(response: StoreMap.DidTapButton.Response)
}

protocol StoreMapRoutingLogic {
    func routeToStoreDetail(store: Store)
    func routeToRegionSelection(message: String?)
}
