//
//  StoreDetailPresenter.swift
//  
//
//  Created by mine on 2020/06/28.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

// MARK: StoreDetailPresenter

class StoreDetailPresenter: ObservableObject {
    
    @Published var viewModel = StoreDetail.ViewModel()
    
    deinit {
        print(#function, #file)
    }
    
}

// MARK: StoreDetailPresentationLogic

extension StoreDetailPresenter: StoreDetailPresentationLogic {
    func present(_ response: StoreDetail.Response) {
        switch response {
        case let .textCount(count):
            viewModel.alert = CommonViewModel.Alert(
                id: 100,
                title: "",
                message: "\(count)자 입력하셨습니다.",
                confirmTitle: "확인"
            )
        case let .wordCountButton(show):
            viewModel.showWordCountButton = show
        }
    }
}

// MARK: StoreDetailRoutingLogic

extension StoreDetailPresenter: StoreDetailRoutingLogic {
    
}

