//
//  StoreMapModels.swift
//  
//
//  Created by mine on 2020/06/28.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum StoreDetail {
    // MARK: Use cases
    enum Request {
        struct DidFinishWriting {
            let message: String
        }
    }
    
    enum Response {
    }
    
    enum ViewModel {
    }
}
