//
//  StoreDetailRouter.swift
//  
//
//  Created by mine on 2020/06/28.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import SwiftUI

protocol StoreDetailRoutingLogic {
    #warning("구체타입.")
    var viewController: StoreDetailViewController{ get }
    //func routeToSomewhere(segue: UIStoryboardSegue?)
}

class StoreDetailRouter: NSObject, StoreDetailRoutingLogic {
    var viewController: StoreDetailViewController

    init(viewController: StoreDetailViewController) {
        self.viewController = viewController
    }
}
