//
//  StoreDetailViewController.swift
//  
//
//  Created by mine on 2020/06/28.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import SwiftUI


// SwiftUI 뷰에서 사용
protocol StoreDetailViewControllingLogic: ViewControllingLogic {
    
}

protocol StoreDetailDisplayLogic: class {
    func displaySomething(viewModel: StoreDetail.Something.ViewModel)
}

class StoreDetailViewController {
    var interactor: StoreDetailBusinessLogic?
    
}

extension StoreDetailViewController: ObservableObject, StoreDetailViewControllingLogic {
    func display(_ destination: ViewControllingLogic) {
        #warning("TODO")
    }
    
    func exit() {
        #warning("TODO")
    }
}

extension StoreDetailViewController: StoreDetailDisplayLogic {
    func displaySomething(viewModel: StoreDetail.Something.ViewModel) {
        //nameTextField.text = viewModel.name
    }
}
