//
//  StoreDetailPresenter.swift
//  
//
//  Created by mine on 2020/06/28.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol StoreDetailPresentationLogic {
    func presentSomething(response: StoreDetail.Something.Response)
}

class StoreDetailPresenter: StoreDetailPresentationLogic {
    weak var viewController: StoreDetailDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: StoreDetail.Something.Response) {
        let viewModel = StoreDetail.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
